Completed the Metrics Webapp
AshwinCarvalho999/react-redux-capstone pull request #1
Opened 2022-11-22 14:01 UTC by AshwinCarvalho999

## For the Home page

- Added the Functionality that when the page loads, the web app shows the list of Continents that could be filtered out by the Country name.
- Displayed some numeric values per Country that come from the API.
- Added Navigation for the user to navigate to the details page when the user clicks (or taps) on a Country item.

## For the details page
- Used the API to retrieve the data and to show detailed data in the Country from API.
- Applied the events when the user clicks on the "Back" button (<), the user navigates to the home page.

## For Testing

- Created unit tests for pure functions in Redux code.
- Created integration tests for the application using the React Testing Library.

2022-11-23 14:49 UTC, mikethreels requested changes
Hi Ashwin, 

Good job so far!
There are some issues that you still need to work on to go to the next project but you are almost there!

## Highlights
- linters are passing

## Required Changes ♻️
- [ ] The video should contain a highlight about a piece of the code you find interesting or are proud of making. please reshoot the video and make sure to add this.
_Check the comments under the review._

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-11-24 06:01 UTC, Bondok6 approved these changes
# STATUS: APPROVED :green_circle: :clap: 

## Hi @AshwinCarvalho999 🙋‍♂️, 
Your project is complete!  There is nothing else to say other than... Great job 👏 
Congratulations! 🎉 

TO HIGHLIGHT:

- Great video presentation ✅
- Your project is professional ✅
- Great job using Redux, Store ✅
- Your repo is professional ✅
- Well structured files ✅
- No Linter errors ✅
- Professional README.md file 💯


Now you can merge this branch and move on :1st_place_medal: 
HAPPY CODING AND GOOD LUCK WITH THE COMMING ONES :crossed_fingers: :four_leaf_clover: 

<img src="https://camo.githubusercontent.com/54a5d803a138b5a1a1242a607e4c1192c852cab8c591c1ddcaa33d06b51560f6/68747470733a2f2f6d656469612e67697068792e636f6d2f6d656469612f686c516559335062684833692f67697068792e676966" />


## Optional suggestions

- [ ] _ Check my comments below ⬇

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-11-24 06:01 UTC, Bondok6 commented on README.md
> +
- [OPTIONAL] Great job adding MIT file 💯 
I just suggest removing this `NOTE ...` recommendation from your README file 👍

2022-11-24 06:01 UTC, Bondok6 commented on README.md
> +
- [OPTIONAL] According to the requirements, The README should contain an "Acknowledgements" section or similar that gives appropriate credit to [Nelson Sakwa](https://www.behance.net/sakwadesignstudio) the [author of the original design](https://www.behance.net/gallery/31579789/Ballhead-App-(Free-PSDs)), as required by the [Creative Commons License](https://creativecommons.org/licenses/). 💯

![image](https://user-images.githubusercontent.com/45231276/203704400-bf3d4ac0-1562-4cf5-b189-c6312141d55c.png)

> I marked this as Optional because it's missed by the previous reviewer. However, I strongly recommend you to take them into account 👍

2022-11-24 06:01 UTC, Bondok6 commented on src/_tests_/Navbar.test.js
> +
- [OPTIONAL] Please make sure that all tests are passed correctly, because I got some 
issues when I run `npm run test` 👍

2022-11-24 06:07 UTC, merged